"""baseline schema

Revision ID: 736cd65ce774
Revises: 
Create Date: 2026-06-18 07:44:26.229542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736cd65ce774'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('diesel_eom', sa.Float(), nullable=False),
    sa.Column('bal_30s', sa.Float(), nullable=False),
    sa.Column('bal_12n', sa.Float(), nullable=False),
    sa.Column('bal_12ff', sa.Float(), nullable=False),
    sa.Column('bal_12nl', sa.Float(), nullable=False),
    sa.Column('pallets_wrapped', sa.Float(), nullable=False),
    sa.Column('bales_used', sa.Float(), nullable=False),
    sa.Column('bales_purchased', sa.Float(), nullable=False),
    sa.Column('labels_used', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_stock_period'), ['period'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('operator', 'supervisor', 'manager', 'admin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('auth_source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('bale_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('grn', sa.String(length=60), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bale_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bale_receipts_work_date'), ['work_date'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=False),
    sa.Column('tray30', sa.Float(), nullable=False),
    sa.Column('tray12n', sa.Float(), nullable=False),
    sa.Column('tray12ff', sa.Float(), nullable=False),
    sa.Column('pallets', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_work_date'), ['work_date'], unique=False)

    op.create_table('fuel_dips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=30), nullable=False),
    sa.Column('open_dip', sa.Float(), nullable=False),
    sa.Column('close_dip', sa.Float(), nullable=False),
    sa.Column('actual_usage', sa.Float(), nullable=False),
    sa.Column('received', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_dips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_dips_work_date'), ['work_date'], unique=False)

    op.create_table('production_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Enum('day', 'afternoon', 'night', name='shift'), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('p30s', sa.Float(), nullable=False),
    sa.Column('p30l', sa.Float(), nullable=False),
    sa.Column('p20n', sa.Float(), nullable=False),
    sa.Column('p12n', sa.Float(), nullable=False),
    sa.Column('p12hf', sa.Float(), nullable=False),
    sa.Column('p12ff', sa.Float(), nullable=False),
    sa.Column('p4cup', sa.Float(), nullable=False),
    sa.Column('p2cup', sa.Float(), nullable=False),
    sa.Column('hp1', sa.Float(), nullable=False),
    sa.Column('hp2', sa.Float(), nullable=False),
    sa.Column('hp3', sa.Float(), nullable=False),
    sa.Column('hp4', sa.Float(), nullable=False),
    sa.Column('hp5', sa.Float(), nullable=False),
    sa.Column('hp6', sa.Float(), nullable=False),
    sa.Column('labelling', sa.Float(), nullable=False),
    sa.Column('water_meter', sa.Float(), nullable=False),
    sa.Column('carton_bales', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('fuel_open', sa.Float(), nullable=False),
    sa.Column('fuel_close', sa.Float(), nullable=False),
    sa.Column('fuel_use', sa.Float(), nullable=False),
    sa.Column('prod_hours', sa.Float(), nullable=False),
    sa.Column('downtime_min', sa.Float(), nullable=False),
    sa.Column('sched_hours', sa.Float(), nullable=False),
    sa.Column('clean_min', sa.Float(), nullable=False),
    sa.Column('mold_min', sa.Float(), nullable=False),
    sa.Column('other_min', sa.Float(), nullable=False),
    sa.Column('repulped', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_date', 'shift', name='uq_date_shift')
    )
    with op.batch_alter_table('production_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_shifts_shift'), ['shift'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_shifts_work_date'), ['work_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_shifts_work_date'))
        batch_op.drop_index(batch_op.f('ix_production_shifts_shift'))

    op.drop_table('production_shifts')
    with op.batch_alter_table('fuel_dips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_dips_work_date'))

    op.drop_table('fuel_dips')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_work_date'))

    op.drop_table('deliveries')
    with op.batch_alter_table('bale_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bale_receipts_work_date'))

    op.drop_table('bale_receipts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('monthly_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_stock_period'))

    op.drop_table('monthly_stock')
    # ### end Alembic commands ###
